name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Run Lint
                run: ./gradlew lintDebug

            -   name: Upload html test report
                if: always()
                uses: actions/upload-artifact@v4
                with:
                    name: lint-report
                    path: app/build/reports/lint-results-debug.html

    test:
        needs: [ lint ]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the code
                uses: actions/checkout@v4

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Run tests
                run: ./gradlew test

            -   name: Upload test report
                uses: actions/upload-artifact@v4
                with:
                    name: unit-test-report
                    path: app/build/reports/tests/testDebugUnitTest/

    instrumentation-test:
        needs: [ test ]
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the code
                uses: actions/checkout@v4

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Install Android SDK
                uses: android-actions/setup-android@v3

            -   name: Run instrumentation tests
                run: ./gradlew managedDeviceAndroidTest

            -   name: Upload test report
                uses: actions/upload-artifact@v4
                with:
                    name: unit-test-report
                    path: app/build/reports/androidTests/connected/
